### PR TITLE
refactor: overhaul filtering to allow for multiple types of limit IDs

### PR DESCRIPTION
**Pull request by ocn**
This PR introduces a lot of changes. Allow me to detail them by category:

Project files:
* don't nest the source code dir or build-time scripts like Dockerfiles and JS/TS configuration files
* minimize re-build necessary in multi-stage dockerfile

Functionality:
* add support for filtering by ship-group-type ID
* add support for multiple limit IDs **and** multiple _types_ of limit IDs, e.g. filter for kills in a region by 1-or-more alliance IDs **and** 1-or-more ship-group-type IDs
* add regional, ship-type filters to the public killfeed. More options can be added to the public kill feed option, and it should **supersede** the need for any of the other specific feeds (e.g. I can create a public filter that limits by system/constellation/region AND ship-type AND minimum-value)
* handle websocket closures by auto-restarting the websocket connection, also handled websocket errors by closing the websocket (and thus auto-restarting)
* improved logging

TODO: 
* Undo changes to README
* Improve README to detail the new multiple limit-ID options for the public (and other) feeds
* Add support for negative ship-group-type ID filtering (along with alliance/character/etc), which will allow for excluding kills based on a limit ID
* Add an easy flag for limiting kills to a certain type of space, e.g. highsec, lowsec, nullsec, pochven, wormholes (i.e. a user is able to choose one or more to include or exclude)

### CODE REVIEW

**Comment by sven-codeculture** [comment]
thats a bit to much of a change for my taste :) 
ill try to pickout stuff needed.

**Comment by SvenBrnn** [comment]
thanks for the PR, however its a bit to much change for my tastes :)

**Comment by SvenBrnn** [comment]
Thanks for the PR, ill close it as this is to much of a code change.
Just a small info, you need to be careful when forking stuff and editing the Readme files. You changed the copyright to your own name. If i was someone who would do such things, i could make you big problems now.
The use of the code was allowed with including the copyright to the original owner due to the licence you included. You however changed the name to yourself, claiming that you are the original owner of the code. If you do this on other projects it meight lead to seriouse problems for you as you break copyright law with it, so be careful.

BTW this is just a info. I don't really mind it that much.

**Comment by ocn** [comment]
> You changed the copyright to your own name. If i was someone who would do such things, i could make you big problems now. The use of the code was allowed with including the copyright to the original owner due to the licence you included. You however changed the name to yourself, claiming that you are the original owner of the code. If you do this on other projects it meight lead to seriouse problems for you as you break copyright law with it, so be careful.

This is not the case because you have licensed your codebase as MIT.

MIT:
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

Sublicensing is permitted under your license, "without restriction" and provided "as-is". I can take it, say I made it, sell it for money, and relicense it under MIT.

See [TLDRLegal](https://tldrlegal.com/license/mit-license) for more details.

**Pull request closed without merging**
